name: Automatically add the issue to the project board
on:
  issues:
    types: [opened]
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@0.3.0
        with:
          project-url: "https://github.com/orgs/Nordland-fylkeskommune/projects/5"
          github-token: ${{ secrets.GITHUB_TOKEN }}
